version: '3'

services:
  overture:
    image: ccr.ccs.tencentyun.com/dovlov/overture
    container_name: overture
    network_mode: "host"
    # If you'd like to use your own config, mount volums as follows.
    # NOTE: you have to create and edit these files in advance.
    # volumes:
    #   - ./overture/config.yaml:/overture/config.yaml
    #   - ./overture/domain_primary:/overture/domain_primary_sample
    #   - ./overture/domain_alternative:/overture/domain_alternative_sample
    #   - ./overture/ip_network_primary:/overture/ip_network_primary_sample
    #   - ./overture/ip_network_alternative:/overture/ip_network_alternative_sample
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
          max-size: "128k"

  redis:
    image: redis:alpine
    container_name: overture-redis
    ports:
      - 127.0.0.1:56379:6379
    restart: unless-stopped