version: '3'

services:
  overture:
    image: ghcr.io/apocalypsor/overture:upstream
    container_name: smartdns
    network_mode: "host"
    volumes:
      - ./conf:/conf
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
          max-size: "128k"
